import type { FhirResource } from '../lib/types'
const now=()=>new Date().toISOString()
const ambulatoryClass={system:'http://terminology.hl7.org/CodeSystem/v3-ActCode',code:'AMB',display:'ambulatory'}
const attenderType={coding:[{system:'http://terminology.hl7.org/CodeSystem/v3-ParticipationType',code:'ATND',display:'attender'}]}
export function encounterResource(x:{org:string;patient:string;practitioner:string;location:string}):FhirResource{const startedAt=now();return {resourceType:'Encounter',identifier:[{system:`http://sys-ids.kemkes.go.id/encounter/${x.org}`,use:'official',value:`FHIRCARE-${Date.now()}`}],status:'arrived',statusHistory:[{status:'arrived',period:{start:startedAt,end:startedAt}}],class:ambulatoryClass,subject:{reference:`Patient/${x.patient}`},participant:[{type:[attenderType],individual:{reference:`Practitioner/${x.practitioner}`}}],period:{start:startedAt},location:[{location:{reference:`Location/${x.location}`}}],serviceProvider:{reference:`Organization/${x.org}`}}}
export function conditionResource(x:{patient:string;encounter:string;code:string;display:string}):FhirResource{return {resourceType:'Condition',clinicalStatus:{coding:[{system:'http://terminology.hl7.org/CodeSystem/condition-clinical',code:'active'}]},category:[{coding:[{system:'http://terminology.hl7.org/CodeSystem/condition-category',code:'encounter-diagnosis',display:'Encounter Diagnosis'}]}],code:{coding:[{system:'http://hl7.org/fhir/sid/icd-10',code:x.code,display:x.display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`}}}
export function vitalResource(x:{patient:string;encounter:string;practitioner:string;kind:'temperature'|'weight'|'height';value:number}):FhirResource{const m={temperature:['8310-5','Body temperature','Cel'],weight:['29463-7','Body weight','kg'],height:['8302-2','Body height','cm']} as const;const[code,display,unit]=m[x.kind];return {resourceType:'Observation',status:'final',category:[{coding:[{system:'http://terminology.hl7.org/CodeSystem/observation-category',code:'vital-signs',display:'Vital Signs'}]}],code:{coding:[{system:'http://loinc.org',code,display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},effectiveDateTime:now(),performer:[{reference:`Practitioner/${x.practitioner}`}],valueQuantity:{value:x.value,unit,system:'http://unitsofmeasure.org',code:unit}}}
export function bpResource(x:{patient:string;encounter:string;practitioner:string;systolic:number;diastolic:number}):FhirResource{return {resourceType:'Observation',status:'final',category:[{coding:[{system:'http://terminology.hl7.org/CodeSystem/observation-category',code:'vital-signs'}]}],code:{coding:[{system:'http://loinc.org',code:'85354-9',display:'Blood pressure panel'}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},effectiveDateTime:now(),performer:[{reference:`Practitioner/${x.practitioner}`}],component:[{code:{coding:[{system:'http://loinc.org',code:'8480-6',display:'Systolic blood pressure'}]},valueQuantity:{value:x.systolic,unit:'mm[Hg]',system:'http://unitsofmeasure.org',code:'mm[Hg]'}},{code:{coding:[{system:'http://loinc.org',code:'8462-4',display:'Diastolic blood pressure'}]},valueQuantity:{value:x.diastolic,unit:'mm[Hg]',system:'http://unitsofmeasure.org',code:'mm[Hg]'}}]}}
export function procedureResource(x:{patient:string;encounter:string;practitioner:string;code:string;display:string}):FhirResource{return {resourceType:'Procedure',status:'completed',code:{coding:[{system:'http://snomed.info/sct',code:x.code,display:x.display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},performedDateTime:now(),performer:[{actor:{reference:`Practitioner/${x.practitioner}`}}]}}
export function serviceRequestResource(x:{org:string;patient:string;encounter:string;practitioner:string;code:string;display:string;kind:'lab'|'rad'}):FhirResource{return {resourceType:'ServiceRequest',identifier:[{system:`http://sys-ids.kemkes.go.id/servicerequest/${x.org}`,value:`FHIRCARE-${x.kind.toUpperCase()}-${Date.now()}`}],status:'active',intent:'original-order',priority:'routine',category:[{coding:[x.kind==='lab'?{system:'http://snomed.info/sct',code:'108252007',display:'Laboratory procedure'}:{system:'http://snomed.info/sct',code:'363679005',display:'Imaging'}]}],code:{coding:[{system:x.kind==='lab'?'http://loinc.org':'http://snomed.info/sct',code:x.code,display:x.display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},authoredOn:now(),requester:{reference:`Practitioner/${x.practitioner}`},performer:[{reference:`Organization/${x.org}`}]}}
export function labObservation(x:{patient:string;encounter:string;org:string;serviceRequest:string;code:string;display:string;value:number;unit:string}):FhirResource{return {resourceType:'Observation',status:'final',category:[{coding:[{system:'http://terminology.hl7.org/CodeSystem/observation-category',code:'laboratory'}]}],code:{coding:[{system:'http://loinc.org',code:x.code,display:x.display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},basedOn:[{reference:`ServiceRequest/${x.serviceRequest}`}],effectiveDateTime:now(),performer:[{reference:`Organization/${x.org}`}],valueQuantity:{value:x.value,unit:x.unit,system:'http://unitsofmeasure.org',code:x.unit}}}
export function diagnosticReport(x:{patient:string;encounter:string;org:string;serviceRequest:string;kind:'lab'|'rad';code:string;display:string;observationId?:string;conclusion?:string}):FhirResource{return {resourceType:'DiagnosticReport',status:'final',category:[{coding:[{system:'http://terminology.hl7.org/CodeSystem/v2-0074',code:x.kind==='lab'?'LAB':'RAD'}]}],code:{coding:[{system:x.kind==='lab'?'http://loinc.org':'http://snomed.info/sct',code:x.code,display:x.display}]},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},basedOn:[{reference:`ServiceRequest/${x.serviceRequest}`}],effectiveDateTime:now(),issued:now(),performer:[{reference:`Organization/${x.org}`}],...(x.observationId?{result:[{reference:`Observation/${x.observationId}`}]}:{}),...(x.conclusion?{conclusion:x.conclusion}:{})}}
export function medicationResource(x:{org:string;kfa:string;display:string}):FhirResource{return {resourceType:'Medication',identifier:[{system:`http://sys-ids.kemkes.go.id/medication/${x.org}`,use:'official',value:`FHIRCARE-MED-${Date.now()}`}],code:{coding:[{system:'http://sys-ids.kemkes.go.id/kfa',code:x.kfa,display:x.display}]},status:'active'}}
export function medicationRequest(x:{org:string;patient:string;encounter:string;practitioner:string;medicationId:string;dose:string}):FhirResource{return {resourceType:'MedicationRequest',identifier:[{system:`http://sys-ids.kemkes.go.id/prescription/${x.org}`,use:'official',value:`FHIRCARE-RX-${Date.now()}`}],status:'active',intent:'order',medicationReference:{reference:`Medication/${x.medicationId}`},subject:{reference:`Patient/${x.patient}`},encounter:{reference:`Encounter/${x.encounter}`},authoredOn:now(),requester:{reference:`Practitioner/${x.practitioner}`},dosageInstruction:[{text:x.dose}]}}
export function medicationDispense(x:{org:string;patient:string;encounter:string;medicationId:string;medicationRequestId:string;quantity:number;unit:string}):FhirResource{return {resourceType:'MedicationDispense',identifier:[{system:`http://sys-ids.kemkes.go.id/prescription-item/${x.org}`,use:'official',value:`FHIRCARE-DISP-${Date.now()}`}],status:'completed',medicationReference:{reference:`Medication/${x.medicationId}`},subject:{reference:`Patient/${x.patient}`},context:{reference:`Encounter/${x.encounter}`},authorizingPrescription:[{reference:`MedicationRequest/${x.medicationRequestId}`}],whenHandedOver:now(),quantity:{value:x.quantity,unit:x.unit,system:'http://unitsofmeasure.org',code:x.unit}}}
