import type { Context } from 'hono'
import { bool, env, satusehatConfig } from './config'
export const ALLOWED=new Set(['Patient','Practitioner','Organization','Location','Encounter','Condition','Observation','Procedure','ServiceRequest','DiagnosticReport','Medication','MedicationRequest','MedicationDispense'])
type Cached={token:string;expiresAt:number};let cache:Cached|null=null
async function token(c:Context){const cfg=satusehatConfig(c);const e=env(c);if(cfg.environment==='production'&&!bool(e.ALLOW_PRODUCTION,false))throw new Error('Production access is disabled. Set ALLOW_PRODUCTION=true only after an explicit safety review.');if(!cfg.clientId||!cfg.clientSecret)throw new Error('SATUSEHAT_CLIENT_ID and SATUSEHAT_CLIENT_SECRET are required');if(cache&&cache.expiresAt>Date.now()+30000)return cache.token;const body=new URLSearchParams({client_id:cfg.clientId,client_secret:cfg.clientSecret});const res=await fetch(`${cfg.authUrl.replace(/\/$/,'')}/accesstoken?grant_type=client_credentials`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await res.json() as any;if(!res.ok||!data.access_token)throw new Error(`SATUSEHAT OAuth failed (${res.status})`);cache={token:data.access_token,expiresAt:Date.now()+Number(data.expires_in||300)*1000};return cache.token}
async function raw(c:Context,method:string,path:string,body?:unknown,retry=true){const cfg=satusehatConfig(c);const access=await token(c);const started=Date.now();const res=await fetch(`${cfg.fhirUrl.replace(/\/$/,'')}${path}`,{method,headers:{Authorization:`Bearer ${access}`,Accept:'application/fhir+json',...(body?{'Content-Type':'application/fhir+json'}:{})},body:body?JSON.stringify(body):undefined});const text=await res.text();let data:unknown;try{data=text?JSON.parse(text):null}catch{data={resourceType:'OperationOutcome',issue:[{severity:'error',code:'exception',diagnostics:text}]}}if(res.status===401&&retry){cache=null;return raw(c,method,path,body,false)}return{ok:res.ok,status:res.status,method,path,elapsedMs:Date.now()-started,request:body,response:data}}
export function assertType(t:string){if(!ALLOWED.has(t))throw new Error(`Resource type not allowed: ${t}`)}
export async function fhirSearch(c:Context,t:string,params:Record<string,string>){assertType(t);const qs=new URLSearchParams();for(const[k,v]of Object.entries(params||{})){if(typeof v==='string'&&v)qs.set(k,v)}const trace=await raw(c,'GET',`/${t}?${qs.toString()}`);return {...trace,request:{searchParams:params}}}
export async function fhirRead(c:Context,t:string,id:string){assertType(t);return raw(c,'GET',`/${t}/${encodeURIComponent(id)}`)}
export async function fhirCreate(c:Context,t:string,resource:unknown){assertType(t);if((resource as any)?.resourceType!==t)throw new Error('resourceType mismatch');return raw(c,'POST',`/${t}`,resource)}
export async function fhirUpdate(c:Context,t:string,id:string,resource:unknown){assertType(t);if((resource as any)?.resourceType!==t)throw new Error('resourceType mismatch');return raw(c,'PUT',`/${t}/${encodeURIComponent(id)}`,resource)}
